# This is a basic workflow to help you get started with Actions

name: QA - Metadata

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        path: tree
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Preparing scripts
      run: |
        git clone https://github.com/AOSC-Dev/abbs-meta --depth=1
        cp abbs-meta/bashvar.py .
        pip3 install --user pyparsing
        git clone https://github.com/AOSC-Dev/scriptlets --depth=1
        cp scriptlets/abbs-ci/bash-check.py .
        
    - name: Running the linter
      run: |
        python bash-check.py tree
